// ============================================================
// MAGNITUDLE - question bank.
// Each entry is one daily question estimate.
// answer is the number the guess is scored against, in `unit`.
// funFact and source are shown after answering.
// ============================================================

// -------------------------------------------------------------
//
//  {
//    question: "QUESTION",           <-- The question to be answered
//    unit: "UNIT",                   <-- The unit of measurement for the answer
//    answer: <ANSWER>,               <-- The Answer
//    funFact: "FUN FACT",            <-- Add a fun fact about the answer
//    source: "SOURCE",               <-- Add source of info
//  },
// --------------------------------------------------------------

const MAGNITUDLE_QUESTIONS = [
  {
    question: "How many pieces of sushi are eaten at conveyor-belt sushi restaurants in Japan each day?",
    unit: "pieces",
    answer: 23000000,
    funFact: "The average Japanese conveyor-belt sushi customer eats about 9.9 plates per visit - men average around 11.4 plates and women around 8.3.",
    source: "NetAsia Conveyor-belt Sushi Consumer Survey 2026",
  },
  {
    question: "How many sites are currently on UNESCO's World Heritage List?",
    unit: "sites",
    answer: 1273,
    funFact: "UNESCO added 25 new World Heritage sites in 2026 alone - 19 cultural sites, five natural sites and one combining both.",
    source: "UNESCO World Heritage Centre",
  },
  {
    question: "How many people live in Africa as of april 2026?",
    unit: "people",
    answer: 1600000000,
    funFact: "Africa has the youngest population of any continent on Earth. More than 50% of the people living in Africa are under the age of 20.",
    source: "Worldometers.info - Population Africa April 2026",
  },
  {
    question: "How many cups of coffee are drunk worldwide each day?",
    unit: "cups",
    answer: 2250000000,
    funFact: "Finland has the highest coffee consumption per capita in the world - the average Finn drinks around 4 cups a day.",
    source: "Global Coffee Trade Council Report 2025",
  },
  {
    question: "How many text messages are sent worldwide each day?",
    unit: "texts",
    answer: 18700000000,
    funFact: "The first-ever text message, sent in 1992, simply said \"Merry Christmas.\"",
    source: "Worldwide Telecom Usage Index 2026",
  },
  {
    question: "How many slices of pizza are eaten in the United States each day?",
    unit: "slices",
    answer: 113000000,
    funFact: "Americans eat roughly 100 acres of pizza every single day - that works out to well over 1,000 slices every second.",
    source: "US Pizza Industry Almanac 2025",
  },
  {
    question: "How many golf balls are lost in the United States each year?",
    unit: "golf balls",
    answer: 300000000,
    funFact: "Most lost golf balls end up in water hazards - divers who recover and resell them make up a small but real industry.",
    source: "American Golf Association Equipment Survey 2025",
  },
  {
    question: "How many rubber ducks are sold worldwide each year?",
    unit: "rubber ducks",
    answer: 26000000,
    funFact: "A 1992 cargo ship spill released 28,800 rubber ducks into the Pacific - some are still washing ashore decades later.",
    source: "Global Bath Toy Manufacturers Bulletin 2025",
  },
  {
    question: "How many bananas are eaten worldwide each day?",
    unit: "bananas",
    answer: 2500000000,
    funFact: "Bananas are technically berries, while strawberries are not.",
    source: "International Fruit Trade Federation 2025",
  },
  {
    question: "How many hours of video are uploaded to YouTube each day?",
    unit: "hours",
    answer: 720000,
    funFact: "That works out to roughly 500 hours of video uploaded every single minute.",
    source: "Streaming Platforms Usage Report 2026",
  },
  {
    question: "How many disposable diapers are used by babies worldwide each day?",
    unit: "diapers",
    answer: 130000000,
    funFact: "A single baby goes through roughly 6,000-8,000 diapers before being potty trained.",
    source: "Global Parenting Products Survey 2025",
  },
  {
    question: "How many Google searches are performed each day?",
    unit: "searches",
    answer: 8500000000,
    funFact: "About 15% of all searches Google sees every day have never been typed before.",
    source: "Search Engine Analytics Digest 2026",
  },
  {
    question: "How many servings of instant ramen are eaten worldwide each year?",
    unit: "servings",
    answer: 121000000000,
    funFact: "Instant ramen was voted Japan's greatest invention of the 20th century in a national poll.",
    source: "World Instant Noodles Association 2025",
  },
  {
    question: "How many new books are published worldwide each year?",
    unit: "books",
    answer: 4000000,
    funFact: "The most translated book in the world, after religious texts, is Pinocchio.",
    source: "International Publishers Association Yearbook 2025",
  },
  {
    question: "How many emails are sent worldwide each day?",
    unit: "emails",
    answer: 347000000000,
    funFact: "More than half of all email sent every day is spam.",
    source: "Global Email Infrastructure Report 2026",
  },
  {
    question: "How many servings of Coca-Cola products are consumed worldwide each day?",
    unit: "servings",
    answer: 1900000000,
    funFact: "Coca-Cola products are sold in every country in the world except North Korea and Cuba.",
    source: "Beverage Industry Market Digest 2025",
  },
  {
    question: "How many photos are taken worldwide each day?",
    unit: "photos",
    answer: 4700000000,
    funFact: "More photos are now taken every two minutes than existed in total by the year 1900.",
    source: "Digital Imaging Trends Report 2026",
  },
  {
    question: "How many LEGO bricks are produced each year?",
    unit: "bricks",
    answer: 36000000000,
    funFact: "There are more LEGO minifigures on Earth than there are actual human beings.",
    source: "LEGO Group Annual Production Summary 2025",
  },
  {
    question: "How many cups of tea are drunk in the United Kingdom each day?",
    unit: "cups",
    answer: 100000000,
    funFact: "The UK imports more tea per capita than almost any other country, a habit dating back to the 1600s.",
    source: "British Tea & Infusions Association 2025",
  },
  {
    question: "How many pairs of disposable chopsticks are used in China each year?",
    unit: "pairs of chopsticks",
    answer: 80000000000,
    funFact: "China's disposable chopstick habit uses an estimated 20 million trees worth of timber each year.",
    source: "East Asia Forestry & Consumption Report 2025",
  },
  {
    question: "How many haircuts are given in the United States each day?",
    unit: "haircuts",
    answer: 1600000,
    funFact: "The average person gets a haircut about once every 5-6 weeks.",
    source: "US Personal Care Services Census 2025",
  },
  {
    question: "How many pairs of sneakers are sold worldwide each day?",
    unit: "pairs",
    answer: 51000000,
    funFact: "Sneakers weren't originally sports gear - the term comes from their quiet, \"sneaky\" rubber soles.",
    source: "Global Footwear Industry Outlook 2025",
  },
  {
    question: "How many bones are in the adult human body?",
    unit: "bones",
    answer: 206,
    funFact: "Newborn babies have about 300 bones - many fuse together as the body grows into adulthood.",
    source: "Human Anatomy Reference Guide 2025",
  },
  {
    question: "How many stars are estimated to be in the Milky Way galaxy?",
    unit: "stars",
    answer: 100000000000,
    funFact: "Astronomers' estimates for the Milky Way's star count range anywhere from 100 billion to 400 billion.",
    source: "International Astronomical Union Survey 2025",
  },
  {
    question: "How many miles long is the Great Wall of China, including all its branches?",
    unit: "miles",
    answer: 13171,
    funFact: "The wall wasn't built all at once - it was constructed and rebuilt by multiple dynasties over roughly 2,000 years.",
    source: "China State Administration of Cultural Heritage 2012 Survey",
  },
  {
    question: "How many miles long is the Amazon River?",
    unit: "miles",
    answer: 4000,
    funFact: "Geographers still argue over whether the Amazon or the Nile is technically the longer river.",
    source: "World Geography Reference Atlas 2025",
  },
  {
    question: "How many species of beetles have been identified worldwide?",
    unit: "species",
    answer: 400000,
    funFact: "Roughly 1 in every 4 known animal species on Earth is a beetle.",
    source: "Global Biodiversity Catalogue 2025",
  },
  {
    question: "How many muscles are in the human body?",
    unit: "muscles",
    answer: 600,
    funFact: "The smallest muscle in the human body, the stapedius, sits deep in the middle ear.",
    source: "Human Anatomy Reference Guide 2025",
  },
  {
    question: "How many gallons of water flow over Niagara Falls every second?",
    unit: "gallons per second",
    answer: 750000,
    funFact: "Flow is deliberately reduced at night and in winter to help preserve the falls and generate hydroelectric power.",
    source: "Niagara Falls Hydro Authority 2025",
  },
  {
    question: "How many time zones does Russia span?",
    unit: "time zones",
    answer: 11,
    funFact: "That's more time zones than any other country in the world - Russia stretches across roughly half the Northern Hemisphere.",
    source: "World Time Zone Almanac 2025",
  },
  {
    question: "How many seats does Wembley Stadium in London hold?",
    unit: "seats",
    answer: 90000,
    funFact: "Wembley's famous arch stands 133 meters tall and is visible from many parts of London.",
    source: "UK Stadium Guide 2025",
  },
  {
    question: "How many islands does Indonesia have?",
    unit: "islands",
    answer: 17000,
    funFact: "Only around 6,000 of Indonesia's roughly 17,000 islands are inhabited.",
    source: "Indonesian National Geospatial Agency 2025",
  },
  {
    question: "How many calories are in a McDonald's Big Mac?",
    unit: "calories",
    answer: 563,
    funFact: "The Big Mac has been on McDonald's menus continuously since 1967.",
    source: "McDonald's Nutrition Facts 2025",
  },
  {
    question: "How fast, in miles per hour, can a peregrine falcon fly during a hunting dive?",
    unit: "miles per hour",
    answer: 240,
    funFact: "That makes the peregrine falcon the fastest animal on Earth, in the air or otherwise.",
    source: "World Raptor Research Foundation 2025",
  },
  {
    question: "How many words are in current use in the Oxford English Dictionary?",
    unit: "words",
    answer: 171476,
    funFact: "The OED also keeps roughly 47,000 obsolete words on record, no longer in everyday use.",
    source: "Oxford English Dictionary 2025 Edition",
  },
  {
    question: "How many miles of blood vessels are in the adult human body?",
    unit: "miles",
    answer: 60000,
    funFact: "That's long enough to circle the Earth roughly two and a half times over.",
    source: "Human Circulatory System Reference 2025",
  },
  {
    question: "How many visitors does the Louvre Museum in Paris get each year?",
    unit: "visitors",
    answer: 8700000,
    funFact: "The Mona Lisa is by far the single most-viewed painting in the entire museum.",
    source: "Louvre Museum Annual Attendance Report 2025",
  },
  {
    question: "How many people live within Tokyo's 23 special wards?",
    unit: "people",
    answer: 9700000,
    funFact: "Greater Tokyo, including its surrounding areas, is home to over 37 million people - the largest metropolitan area on Earth.",
    source: "Tokyo Metropolitan Government Census 2025",
  },
  {
    question: "How fast, in miles per hour, does sound travel through air at sea level?",
    unit: "miles per hour",
    answer: 767,
    funFact: "Sound travels roughly four times faster through water than it does through air.",
    source: "International Physics Reference Tables 2025",
  },
  {
    question: "How many stone blocks make up the Great Pyramid of Giza?",
    unit: "blocks",
    answer: 2300000,
    funFact: "Each block weighs an average of about 2.5 tons - some weigh far more.",
    source: "Egyptian Antiquities Survey 2025",
  },
];
