// ============================================================
// Popular character tags + approximate post counts on rule34.xxx
// Counts are snapshots (not live).
// img = SFW avatar (DiceBear initials). Letter fallback if load fails.
// ============================================================

const CHARACTERS = [
  { name: "2B", tag: "2b_(nier)", count: 185000, img: "https://api.dicebear.com/9.x/initials/svg?seed=2B&backgroundColor=9d6271&fontWeight=700&fontSize=42" },
  { name: "Asuka Langley", tag: "souryuu_asuka_langley", count: 92000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Asuka%20Langley&backgroundColor=793d52&fontWeight=700&fontSize=42" },
  { name: "Hatsune Miku", tag: "hatsune_miku", count: 210000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Hatsune%20Miku&backgroundColor=345750&fontWeight=700&fontSize=42" },
  { name: "Rem", tag: "rem_(re:zero)", count: 78000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Rem&backgroundColor=856e78&fontWeight=700&fontSize=42" },
  { name: "Zero Two", tag: "zero_two_(darling_in_the_franxx)", count: 95000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Zero%20Two&backgroundColor=734575&fontWeight=700&fontSize=42" },
  { name: "Chun-Li", tag: "chun-li", count: 68000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Chun-Li&backgroundColor=6c646d&fontWeight=700&fontSize=42" },
  { name: "Tifa Lockhart", tag: "tifa_lockhart", count: 72000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Tifa%20Lockhart&backgroundColor=955536&fontWeight=700&fontSize=42" },
  { name: "Samus Aran", tag: "samus_aran", count: 55000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Samus%20Aran&backgroundColor=337457&fontWeight=700&fontSize=42" },
  { name: "Marisa Kirisame", tag: "kirisame_marisa", count: 48000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Marisa%20Kirisame&backgroundColor=537264&fontWeight=700&fontSize=42" },
  { name: "Reimu Hakurei", tag: "hakurei_reimu", count: 52000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Reimu%20Hakurei&backgroundColor=3fa74f&fontWeight=700&fontSize=42" },
  { name: "Hinata Hyuga", tag: "hyuuga_hinata", count: 41000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Hinata%20Hyuga&backgroundColor=56818a&fontWeight=700&fontSize=42" },
  { name: "Sakura Haruno", tag: "haruno_sakura", count: 38000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Sakura%20Haruno&backgroundColor=7b6c70&fontWeight=700&fontSize=42" },
  { name: "Nezuko Kamado", tag: "kamado_nezuko", count: 45000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Nezuko%20Kamado&backgroundColor=9642a0&fontWeight=700&fontSize=42" },
  { name: "Mikasa Ackerman", tag: "mikasa_ackerman", count: 32000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Mikasa%20Ackerman&backgroundColor=4e696a&fontWeight=700&fontSize=42" },
  { name: "Annie Leonhart", tag: "annie_leonhart", count: 18000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Annie%20Leonhart&backgroundColor=4d7530&fontWeight=700&fontSize=42" },
  { name: "Power", tag: "power_(chainsaw_man)", count: 28000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Power&backgroundColor=887785&fontWeight=700&fontSize=42" },
  { name: "Makima", tag: "makima_(chainsaw_man)", count: 35000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Makima&backgroundColor=916a59&fontWeight=700&fontSize=42" },
  { name: "Yor Forger", tag: "yor_briar", count: 22000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Yor%20Forger&backgroundColor=463431&fontWeight=700&fontSize=42" },
  { name: "Anya Forger", tag: "anya_forger", count: 15000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Anya%20Forger&backgroundColor=4c717e&fontWeight=700&fontSize=42" },
  { name: "Frieren", tag: "frieren", count: 19000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Frieren&backgroundColor=3f9d70&fontWeight=700&fontSize=42" },
  { name: "Fern", tag: "fern_(sousou_no_frieren)", count: 12000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Fern&backgroundColor=81864f&fontWeight=700&fontSize=42" },
  { name: "Aqua", tag: "aqua_(konosuba)", count: 34000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Aqua&backgroundColor=43874d&fontWeight=700&fontSize=42" },
  { name: "Megumin", tag: "megumin", count: 42000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Megumin&backgroundColor=3e6e2e&fontWeight=700&fontSize=42" },
  { name: "Darkness", tag: "darkness_(konosuba)", count: 25000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Darkness&backgroundColor=58558b&fontWeight=700&fontSize=42" },
  { name: "Emilia", tag: "emilia_(re:zero)", count: 31000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Emilia&backgroundColor=6f828b&fontWeight=700&fontSize=42" },
  { name: "Ram", tag: "ram_(re:zero)", count: 24000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Ram&backgroundColor=2c7a8d&fontWeight=700&fontSize=42" },
  { name: "Beatrice", tag: "beatrice_(re:zero)", count: 16000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Beatrice&backgroundColor=946253&fontWeight=700&fontSize=42" },
  { name: "Raphtalia", tag: "raphtalia", count: 27000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Raphtalia&backgroundColor=987d52&fontWeight=700&fontSize=42" },
  { name: "Filo", tag: "filo_(tate_no_yuusha)", count: 14000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Filo&backgroundColor=3c689e&fontWeight=700&fontSize=42" },
  { name: "Naofumi", tag: "iwatani_naofumi", count: 9000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Naofumi&backgroundColor=37a380&fontWeight=700&fontSize=42" },
  { name: "Widowmaker", tag: "widowmaker", count: 48000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Widowmaker&backgroundColor=73648f&fontWeight=700&fontSize=42" },
  { name: "Tracer", tag: "tracer", count: 36000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Tracer&backgroundColor=9e74a3&fontWeight=700&fontSize=42" },
  { name: "D.Va", tag: "d.va_(overwatch)", count: 52000, img: "https://api.dicebear.com/9.x/initials/svg?seed=D.Va&backgroundColor=633f8b&fontWeight=700&fontSize=42" },
  { name: "Mercy", tag: "mercy", count: 29000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Mercy&backgroundColor=564761&fontWeight=700&fontSize=42" },
  { name: "Jinx", tag: "jinx_(league_of_legends)", count: 41000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Jinx&backgroundColor=9a3236&fontWeight=700&fontSize=42" },
  { name: "Ahri", tag: "ahri", count: 58000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Ahri&backgroundColor=665897&fontWeight=700&fontSize=42" },
  { name: "Lux", tag: "lux", count: 22000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Lux&backgroundColor=a56182&fontWeight=700&fontSize=42" },
  { name: "Miss Fortune", tag: "miss_fortune", count: 19000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Miss%20Fortune&backgroundColor=897b89&fontWeight=700&fontSize=42" },
  { name: "Cammy", tag: "cammy", count: 31000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Cammy&backgroundColor=95337c&fontWeight=700&fontSize=42" },
  { name: "Mai Shiranui", tag: "mai_shiranui", count: 44000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Mai%20Shiranui&backgroundColor=4f7765&fontWeight=700&fontSize=42" },
  { name: "Princess Peach", tag: "princess_peach", count: 38000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Princess%20Peach&backgroundColor=a63860&fontWeight=700&fontSize=42" },
  { name: "Rosalina", tag: "rosalina", count: 21000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Rosalina&backgroundColor=7fa768&fontWeight=700&fontSize=42" },
  { name: "Zelda", tag: "princess_zelda", count: 33000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Zelda&backgroundColor=786e89&fontWeight=700&fontSize=42" },
  { name: "Link", tag: "link", count: 28000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Link&backgroundColor=718f3f&fontWeight=700&fontSize=42" },
  { name: "Ganondorf", tag: "ganondorf", count: 8000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Ganondorf&backgroundColor=a3a573&fontWeight=700&fontSize=42" },
  { name: "Bayonetta", tag: "bayonetta", count: 24000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Bayonetta&backgroundColor=7d802c&fontWeight=700&fontSize=42" },
  { name: "Ciri", tag: "cirilla_fiona_elen_rianon", count: 17000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Ciri&backgroundColor=63605d&fontWeight=700&fontSize=42" },
  { name: "Yennefer", tag: "yennefer", count: 15000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Yennefer&backgroundColor=452d2c&fontWeight=700&fontSize=42" },
  { name: "Triss", tag: "triss_merigold", count: 12000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Triss&backgroundColor=588170&fontWeight=700&fontSize=42" },
  { name: "Geralt", tag: "geralt_of_rivia", count: 9000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Geralt&backgroundColor=32707c&fontWeight=700&fontSize=42" },
  { name: "Lara Croft", tag: "lara_croft", count: 26000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Lara%20Croft&backgroundColor=9da34b&fontWeight=700&fontSize=42" },
  { name: "Ada Wong", tag: "ada_wong", count: 23000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Ada%20Wong&backgroundColor=7e775a&fontWeight=700&fontSize=42" },
  { name: "Jill Valentine", tag: "jill_valentine", count: 18000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Jill%20Valentine&backgroundColor=2f402a&fontWeight=700&fontSize=42" },
  { name: "Quiet", tag: "quiet_(metal_gear)", count: 14000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Quiet&backgroundColor=7b2f31&fontWeight=700&fontSize=42" },
  { name: "Cortana", tag: "cortana", count: 11000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Cortana&backgroundColor=9d7ba4&fontWeight=700&fontSize=42" },
  { name: "Aloy", tag: "aloy", count: 8000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Aloy&backgroundColor=287282&fontWeight=700&fontSize=42" },
  { name: "Ellie", tag: "ellie_(the_last_of_us)", count: 13000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Ellie&backgroundColor=95427c&fontWeight=700&fontSize=42" },
  { name: "Abby", tag: "abby_(the_last_of_us)", count: 7000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Abby&backgroundColor=4b613e&fontWeight=700&fontSize=42" },
  { name: "A2", tag: "a2_(nier)", count: 22000, img: "https://api.dicebear.com/9.x/initials/svg?seed=A2&backgroundColor=9e656e&fontWeight=700&fontSize=42" },
  { name: "Asuna", tag: "asuna_(sao)", count: 36000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Asuna&backgroundColor=a05ea0&fontWeight=700&fontSize=42" },
  { name: "Sinon", tag: "sinon", count: 19000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Sinon&backgroundColor=934a62&fontWeight=700&fontSize=42" },
  { name: "Kirito", tag: "kirito", count: 14000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Kirito&backgroundColor=7195a6&fontWeight=700&fontSize=42" },
  { name: "Erza Scarlet", tag: "erza_scarlet", count: 28000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Erza%20Scarlet&backgroundColor=6b2a97&fontWeight=700&fontSize=42" },
  { name: "Lucy Heartfilia", tag: "lucy_heartfilia", count: 21000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Lucy%20Heartfilia&backgroundColor=6a672a&fontWeight=700&fontSize=42" },
  { name: "Nami", tag: "nami_(one_piece)", count: 45000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Nami&backgroundColor=48323c&fontWeight=700&fontSize=42" },
  { name: "Nico Robin", tag: "nico_robin", count: 32000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Nico%20Robin&backgroundColor=2d6c33&fontWeight=700&fontSize=42" },
  { name: "Boa Hancock", tag: "boa_hancock", count: 27000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Boa%20Hancock&backgroundColor=4d3479&fontWeight=700&fontSize=42" },
  { name: "Bulma", tag: "bulma", count: 24000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Bulma&backgroundColor=45774d&fontWeight=700&fontSize=42" },
  { name: "Android 18", tag: "android_18", count: 29000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Android%2018&backgroundColor=7b329f&fontWeight=700&fontSize=42" },
  { name: "Rias Gremory", tag: "rias_gremory", count: 31000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Rias%20Gremory&backgroundColor=353c40&fontWeight=700&fontSize=42" },
  { name: "Akeno", tag: "himejima_akeno", count: 26000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Akeno&backgroundColor=2849a4&fontWeight=700&fontSize=42" },
  { name: "Hestia", tag: "hestia_(danmachi)", count: 23000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Hestia&backgroundColor=368b52&fontWeight=700&fontSize=42" },
  { name: "Bell Cranel", tag: "bell_cranel", count: 6000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Bell%20Cranel&backgroundColor=774e8a&fontWeight=700&fontSize=42" },
  { name: "Albedo", tag: "albedo_(overlord)", count: 28000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Albedo&backgroundColor=78a1a0&fontWeight=700&fontSize=42" },
  { name: "Shalltear", tag: "shalltear_bloodfallen", count: 18000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Shalltear&backgroundColor=a38767&fontWeight=700&fontSize=42" },
  { name: "Miku Nakano", tag: "nakano_miku", count: 16000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Miku%20Nakano&backgroundColor=a55036&fontWeight=700&fontSize=42" },
  { name: "Nino Nakano", tag: "nakano_nino", count: 17000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Nino%20Nakano&backgroundColor=652e8a&fontWeight=700&fontSize=42" },
  { name: "Itsuki Nakano", tag: "nakano_itsuki", count: 11000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Itsuki%20Nakano&backgroundColor=6c58a2&fontWeight=700&fontSize=42" },
  { name: "Rukia", tag: "kuchiki_rukia", count: 15000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Rukia&backgroundColor=5d79a0&fontWeight=700&fontSize=42" },
  { name: "Orihime", tag: "inoue_orihime", count: 12000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Orihime&backgroundColor=2a4886&fontWeight=700&fontSize=42" },
  { name: "Yoruichi", tag: "shihouin_yoruichi", count: 14000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Yoruichi&backgroundColor=7a567b&fontWeight=700&fontSize=42" },
  { name: "Kaguya Shinomiya", tag: "shinomiya_kaguya", count: 13000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Kaguya%20Shinomiya&backgroundColor=7a8a7a&fontWeight=700&fontSize=42" },
  { name: "Chika Fujiwara", tag: "fujiwara_chika", count: 10000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Chika%20Fujiwara&backgroundColor=508292&fontWeight=700&fontSize=42" },
  { name: "Mai Sakurajima", tag: "sakurajima_mai", count: 25000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Mai%20Sakurajima&backgroundColor=879f70&fontWeight=700&fontSize=42" },
  { name: "Rio Futaba", tag: "futaba_rio", count: 8000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Rio%20Futaba&backgroundColor=9d535b&fontWeight=700&fontSize=42" },
  { name: "Komi Shouko", tag: "komi_shouko", count: 14000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Komi%20Shouko&backgroundColor=8c7273&fontWeight=700&fontSize=42" },
  { name: "Nagatoro", tag: "nagatoro", count: 19000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Nagatoro&backgroundColor=76595a&fontWeight=700&fontSize=42" },
  { name: "Raiden Shogun", tag: "raiden_shogun", count: 48000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Raiden%20Shogun&backgroundColor=97783d&fontWeight=700&fontSize=42" },
  { name: "Yae Miko", tag: "yae_miko", count: 42000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Yae%20Miko&backgroundColor=6fa74d&fontWeight=700&fontSize=42" },
  { name: "Ganyu", tag: "ganyu_(genshin_impact)", count: 51000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Ganyu&backgroundColor=659396&fontWeight=700&fontSize=42" },
  { name: "Hu Tao", tag: "hu_tao_(genshin_impact)", count: 39000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Hu%20Tao&backgroundColor=958063&fontWeight=700&fontSize=42" },
  { name: "Zhongli", tag: "zhongli_(genshin_impact)", count: 16000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Zhongli&backgroundColor=a36d32&fontWeight=700&fontSize=42" },
  { name: "Venti", tag: "venti_(genshin_impact)", count: 18000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Venti&backgroundColor=a48086&fontWeight=700&fontSize=42" },
  { name: "Keqing", tag: "keqing_(genshin_impact)", count: 28000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Keqing&backgroundColor=5c4b5f&fontWeight=700&fontSize=42" },
  { name: "Jean", tag: "jean_(genshin_impact)", count: 15000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Jean&backgroundColor=4a8652&fontWeight=700&fontSize=42" },
  { name: "Barbara", tag: "barbara_(genshin_impact)", count: 14000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Barbara&backgroundColor=596184&fontWeight=700&fontSize=42" },
  { name: "Fischl", tag: "fischl_(genshin_impact)", count: 17000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Fischl&backgroundColor=794469&fontWeight=700&fontSize=42" },
  { name: "Nahida", tag: "nahida_(genshin_impact)", count: 22000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Nahida&backgroundColor=813c7b&fontWeight=700&fontSize=42" },
  { name: "Furina", tag: "furina_(genshin_impact)", count: 26000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Furina&backgroundColor=4553a0&fontWeight=700&fontSize=42" },
  { name: "Navia", tag: "navia_(genshin_impact)", count: 11000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Navia&backgroundColor=874043&fontWeight=700&fontSize=42" },
  { name: "Clorinde", tag: "clorinde_(genshin_impact)", count: 9000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Clorinde&backgroundColor=574d4a&fontWeight=700&fontSize=42" },
  { name: "Arlecchino", tag: "arlecchino_(genshin_impact)", count: 13000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Arlecchino&backgroundColor=783a52&fontWeight=700&fontSize=42" },
  { name: "Shenhe", tag: "shenhe_(genshin_impact)", count: 16000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Shenhe&backgroundColor=373d4d&fontWeight=700&fontSize=42" },
  { name: "Eula", tag: "eula_(genshin_impact)", count: 19000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Eula&backgroundColor=574087&fontWeight=700&fontSize=42" },
  { name: "Ayaka", tag: "kamisato_ayaka", count: 24000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Ayaka&backgroundColor=6e72a5&fontWeight=700&fontSize=42" },
  { name: "Ayato", tag: "kamisato_ayato", count: 7000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Ayato&backgroundColor=8d3895&fontWeight=700&fontSize=42" },
  { name: "Yoimiya", tag: "yoimiya_(genshin_impact)", count: 12000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Yoimiya&backgroundColor=7c3898&fontWeight=700&fontSize=42" },
  { name: "Sonic", tag: "sonic_the_hedgehog", count: 22000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Sonic&backgroundColor=8ca63d&fontWeight=700&fontSize=42" },
  { name: "Amy Rose", tag: "amy_rose", count: 18000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Amy%20Rose&backgroundColor=835f2c&fontWeight=700&fontSize=42" },
  { name: "Rouge the Bat", tag: "rouge_the_bat", count: 15000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Rouge%20the%20Bat&backgroundColor=979569&fontWeight=700&fontSize=42" },
  { name: "Blaze", tag: "blaze_the_cat", count: 8000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Blaze&backgroundColor=8ba631&fontWeight=700&fontSize=42" },
  { name: "Isabelle", tag: "isabelle_(animal_crossing)", count: 12000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Isabelle&backgroundColor=692b5e&fontWeight=700&fontSize=42" },
  { name: "Pikachu", tag: "pikachu", count: 35000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Pikachu&backgroundColor=967f73&fontWeight=700&fontSize=42" },
  { name: "Gardevoir", tag: "gardevoir", count: 28000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Gardevoir&backgroundColor=35455a&fontWeight=700&fontSize=42" },
  { name: "Lucario", tag: "lucario", count: 16000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Lucario&backgroundColor=305871&fontWeight=700&fontSize=42" },
  { name: "Mewtwo", tag: "mewtwo", count: 9000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Mewtwo&backgroundColor=4e5a9b&fontWeight=700&fontSize=42" },
  { name: "Umbreon", tag: "umbreon", count: 11000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Umbreon&backgroundColor=68412a&fontWeight=700&fontSize=42" },
  { name: "Eevee", tag: "eevee", count: 14000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Eevee&backgroundColor=437a29&fontWeight=700&fontSize=42" },
  { name: "Lopunny", tag: "lopunny", count: 13000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Lopunny&backgroundColor=462f88&fontWeight=700&fontSize=42" },
  { name: "Vaporeon", tag: "vaporeon", count: 17000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Vaporeon&backgroundColor=7b3986&fontWeight=700&fontSize=42" },
  { name: "Charizard", tag: "charizard", count: 12000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Charizard&backgroundColor=a46b87&fontWeight=700&fontSize=42" },
  { name: "Gengar", tag: "gengar", count: 8000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Gengar&backgroundColor=368248&fontWeight=700&fontSize=42" },
  { name: "Snorlax", tag: "snorlax", count: 5000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Snorlax&backgroundColor=665f5c&fontWeight=700&fontSize=42" },
  { name: "Jigglypuff", tag: "jigglypuff", count: 7000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Jigglypuff&backgroundColor=7a8286&fontWeight=700&fontSize=42" },
  { name: "Mimikyu", tag: "mimikyu", count: 9000, img: "https://api.dicebear.com/9.x/initials/svg?seed=Mimikyu&backgroundColor=2a2e54&fontWeight=700&fontSize=42" },
];

const VALID_CHARACTERS = CHARACTERS.filter(c => c.count > 0 && c.name && c.tag);
